from .num_paragraphs_analysis import analyze_num_paragraphs_content_quiz, analyze_num_paragraphs_reading_speed
from .parse_reading_logs import parse_reading_logs_module, parse_reading_logs_all
from .reading_logs_completion_time import reading_logs_completion_time
