BACKGROUND_SURVEY_SCHEMA = "../../../data/background_survey_schema.csv"
BACKGROUND_SURVEY_DATA = "../../../data/processed_background_survey.csv"
OUTPUT_DIRECTORY = "../../../data"
FILE_NAME = "processed_background_survey"
HCI_SURVEY_DATA = "../../data/impression_survey1.csv"
HCI_SURVEY_SCHEMA = "../../data/HCI_survey_schema.csv"
HCI_CLUSTER_DATA = "../../data/for_clustering_impression_survey1.csv"
BACKGROUND_CLUSTER_DATA = "../../data/for_clustering_processed_background_survey.csv"