class GradeBookSchema:
    STUDENT_NAME = 'Student'
    STUDENT_ID = 'ID'
    SECTION = 'Section'
    LECTURE = 'Lecture'
    LAB = 'Lab'
    OVERALL_PROJECT_SCORE = 'Project Final Score'
    OVERALL_MAIN_ACTIVITIES_SCORE = 'Main Activities Final Score'
    OVERALL_TUTORIAL_ACTIVITIES_SCORE = 'Tutorial Activities Final Score'
    OVERALL_PRE_POST_TESTS_SCORE = 'Pre/Post Tests Final Score'
    OVERALL_READING_LOGS_SCORE = 'Reading Logs Final Score'
    OVERALL_COURSE_SCORE = 'Final Score'
    FINAL_SCORE = 'Overall Final Score'
    PRE_TEST_SCORE = 'Overall Pre-Tests (880658)'
    POST_TEST_SCORE = 'Overall Post-Tests (880660)'
    PRE_TEST_1 = 'Pre-Test 1 [[~20 min]] (563436)'
    MAX_PRE_TEST_1 = 7
    PRE_TEST_2 = 'Pre-Test 2 [[~10 min]] (746540)'
    MAX_PRE_TEST_2 = 3
    PRE_TEST_3 = 'Pre-Test 3 [[~15 min]] (563831)'
    MAX_PRE_TEST_3 = 5
    PRE_TEST_4 = 'Pre-Test 4 [[~10 min]] (595624)'
    MAX_PRE_TEST_4 = 5
    PRE_TEST_5 = 'Pre-Test 5 [[~10 min]] (595630)'
    MAX_PRE_TEST_5 = 6
    PRE_TEST_6 = 'Pre-Test 6 [[~15 min]] (823430)'
    MAX_PRE_TEST_6 = 5
    PRE_TEST_7 = 'Pre-Test 7 [[~10min]] (595636)'
    MAX_PRE_TEST_7 = 7
    PRE_TEST_8 = 'Pre-Test 8 (850507)'
    MAX_PRE_TEST_8 = 4
