class TASurveySchema:
    START_DATE = 'StartDate'
    END_DATE = 'EndDate'
    STATUS = 'Status'
    IP_ADDRESS = 'IPAddress'
    DURATION = 'Duration (in seconds)'
    FINISHED = 'Finished'
    RECORDED_DATE = 'RecordedDate'
    RESPONSE_ID = 'ResponseId'
    RECIPIENT_LAST_NAME = 'RecipientLastName'
    RECIPIENT_FIRST_NAME = 'RecipientFirstName'
    RECIPIENT_EMAIL = 'RecipientEmail'
    EXTERNAL_REFERENCE = 'ExternalReference'
    LATITUDE = 'LocationLatitude'
    LONGITUDE = 'LocationLongitude'
    DISTRIBUTION_CHANNEL = 'DistributionChannel'
    USER_LANGUAGE = 'UserLanguage'
